{{- if or (eq .Values.bunny.enabled false) (and .Values.bunny.db.auth.existingSecretName .Values.bunny.taskApi.auth.existingSecretName) -}}
{{- else -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hutch.bunny.name" . }}
data:
  {{- if .Values.bunny.db.auth.existingSecretName -}}
  {{ else }}
  {{- with (include "hutch.bunny.secrets.db" . | fromYaml) }}
  db_username: {{ .username | b64enc }}
  db_password: {{ .password | b64enc }}
  {{- end -}}
  {{- end -}}
  {{- if .Values.bunny.taskApi.basicAuth.existingSecretName }}
  {{ else }}
  task_api_username: {{ .Values.bunny.taskApi.basicAuth.username | required "The bunny.taskApi.auth.username is required if not using existing secret" | b64enc }}
  task_api_password: {{ .Values.bunny.taskApi.basicAuth.password | required "The bunny.taskApi.auth.password is required if not using existing secret" | b64enc }}
  {{- end }}
{{- end -}}


