{{- if and .Values.bunny.enabled .Values.bunny.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hutch.bunny.serviceAccountName" . }}
  labels:
    {{- include "hutch.bunny.labels" . | nindent 4 }}
  {{- with .Values.bunny.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.bunny.serviceAccount.automount }}
{{- end }}
