{{- if and .Values.relay.enabled .Values.relay.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hutch.relay.serviceAccountName" . }}
  labels:
    {{- include "hutch.relay.labels" . | nindent 4 }}
  {{- with .Values.relay.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.relay.serviceAccount.automount }}
{{- end }}
