{{- if or (eq .Values.relay.enabled false) (and (and .Values.relay.db.auth.existingSecretName .Values.relay.queue.auth.existingSecretName) .Values.relay.upstreamTaskApi.basicAuth.existingSecretName) -}}
{{- else -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hutch.relay.name" . }}
data:
  {{- if .Values.relay.db.auth.existingSecretName }}
  {{ else }}
  db_connection_string: {{ with (include "hutch.relay.secrets.db" . | fromYaml) }}
    {{- list "Host=" .host ";Port=" .port ";Database=" .database ";User Id=" .username ";Password=" .password | join ""  | b64enc | quote }}
  {{- end }}
  {{- end -}}
  {{- if .Values.relay.queue.auth.existingSecretName }}
  {{ else }}
  rabbitmq_connection_string: {{ with (include "hutch.relay.secrets.rabbitmq" . | fromYaml) -}}
    {{- list "amqp://" .username ":" .password "@" .host ":" .port | join ""  | b64enc |  quote }}
  {{- end }}
  {{- end -}}
  {{- if .Values.relay.upstreamTaskApi.basicAuth.existingSecretName }}
  {{ else }}
  upstream_task_api_username: {{ .Values.relay.upstreamTaskApi.basicAuth.username | required "relay.upstreamTaskApi.basicAuth.username is required" | b64enc | quote }}
  upstream_task_api_password: {{ .Values.relay.upstreamTaskApi.basicAuth.password | required "relay.upstreamTaskApi.basicAuth.password is required" | b64enc | quote }}
  {{- end -}}
{{- end -}}


