name: bunny-demo

services:
  db:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: omop

  omop-lite:
    image: ghcr.io/health-informatics-uon/omop-lite
    depends_on:
      - db
    environment:
      DB_PASSWORD: postgres
      DB_NAME: omop
      SYNTHETIC: true

  bunny:
    image: ghcr.io/health-informatics-uon/hutch/bunny:edge
    environment:
      DATASOURCE_DB_USERNAME: postgres
      DATASOURCE_DB_PASSWORD: postgres
      DATASOURCE_DB_DATABASE: omop
      DATASOURCE_DB_DRIVERNAME: postgresql
      DATASOURCE_DB_SCHEMA: public
      DATASOURCE_DB_PORT: 5432
      DATASOURCE_DB_HOST: db
      BUNNY_LOGGER_LEVEL: DEBUG
      TASK_API_BASE_URL: https://localhost:8080/link_connector_api
      TASK_API_USERNAME: username
      TASK_API_PASSWORD: password
      COLLECTION_ID: collection_id
    depends_on:
      omop-lite:
        condition: service_completed_successfully
