name: hutch-bunny

services:
  bunny:
    # We recommend pinning to a version number for your deployment.
    image: ghcr.io/health-informatics-uon/hutch/bunny:edge
    environment:
      - DATASOURCE_DB_USERNAME=postgres
      - DATASOURCE_DB_PASSWORD=postgres
      - DATASOURCE_DB_DATABASE=omop
      - DATASOURCE_DB_DRIVERNAME=postgresql
      - DATASOURCE_DB_SCHEMA=public
      - DATASOURCE_DB_PORT=5432
      - DATASOURCE_DB_HOST=db_host
      - TASK_API_BASE_URL=<task_api_host>/link_connector_api
      - TASK_API_USERNAME=username
      - TASK_API_PASSWORD=password
      - LOW_NUMBER_SUPPRESSION_THRESHOLD=5
      - ROUNDING_TARGET=10
      - POLLING_INTERVAL=5
      - COLLECTION_ID=collection_id
