name: hutch-relay

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672 # expose the management gui to the host
      # - 5672:5672 # but not the amqp server
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  relay:
    # We recommend pinning to a version number for your deployment.
    image: ghcr.io/health-informatics-uon/hutch/relay:edge
    restart: always
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - rabbitmq
    environment:
      # Configuration Docs: https://hutch.health/relay/config
      ConnectionStrings__Default: Server=db_host;Port=5432;Database=hutch_relay;User Id=postgres;Password=postgres
      RelayTaskQueue__ConnectionString: amqp://user:password@rabbitmq:5672

      # Declarative State Config https://hutch.health/relay/config#declarative-config
      DownstreamUsers__username__Password: password
      DownstreamUsers__username_Subnode: 93258ae6-472f-45d2-8cf9-8b64cbeb03c8

      # Query Sources
      Beacon__Enable: true # GA4GH Beacon interface enabled for sample purposes; see additional config: https://hutch.health/relay/config#ga4gh-beacon

      UpstreamTaskApi__Enable: false # change to true and populate below to use with an Upstream Task API https://hutch.health/relay/config#upstream-task-api
      UpstreamTaskApi__BaseUrl: https://my-task-api.com
      UpstreamTaskApi__CollectionId: dd52026b-5a61-4c89-b733-04ba141b3f31
      UpstreamTaskApi__Username: user
      UpstreamTaskApi__Password: password
